version: '3'

tasks:
  setup-dev:
    desc: 'Setup workspace'
    cmds:
      - 'uv sync --all-groups --frozen'
      - 'lefthook install'
  verify:
    desc: 'Verify workspace'
    cmds:
      - 'lefthook run pre-commit --all-files'
